### ISSUE TITLE
incompatible with Plasma 6

### ISSUE THREAD

**Issue by InTheMorning** [duvholt/i3-pager#30] opened 2024-03-16 21:39 UTC
Will not work with Plasma 6 with error message:
"This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. Please contact the widget's author for an updated version."

**Comment by Thaodan** [comment] 2024-04-22 21:37
#32 Everything works except the layout issues in the screenshot below and the color selection in the config panel.

For some reason the widget slips under the others. On another screen the widget is slightly of screen.
![Screenshot_20240423_003457](https://github.com/duvholt/i3-pager/assets/1747359/888efba1-63fa-4e6b-9081-e67d6109a553)

**Comment by Thaodan** [comment] 2024-04-22 21:46
Also the option show only current screen didn't work for me when I mirror one of my 3 screens to the one set on the right side.

**Comment by Bureaucromancer** [comment] 2024-04-29 18:36
Something is breaking the build me, though it’s in i3ipc++.  It seems to think that the event hooks aren’t defined… https://github.com/drmgc/i3ipcpp/issues/43

**Comment by Thaodan** [comment] 2024-04-29 19:21
Different bug?

In any test you should check which version of sigcpp you built against.

**Comment by duvholt** [comment] 2024-05-12 16:58
This issue was mostly fixed by #32 which was merged a couple of weeks ago.
I also fixed the screens configuration page and the plasmoid width just now. For any other bugs please open new issues.

**Closed as completed by duvholt** 2024-05-12 16:58 UTC

**Comment by Thaodan** [comment] 2024-05-12 17:55
> I also fixed the screens configuration page and the plasmoid width just now. For any other bugs please open new issues.

Oh awesome!
Did you notice that the option show only only workspaces from current screen sometimes doesn't work?

**Comment by Thaodan** [comment] 2024-05-12 20:57
The changes work good, the plugin no longer slips under other plasmoids.

However these warnings are there still (not sure which one where there before:
```
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configGeneral.qml:7:1: QML SimpleKCM: Created graphical object was not placed in the graphics scene.
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configGeneral.qml:34:9: QML FormLayout: Binding loop detected for property "width"
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configGeneral.qml:34:9: QML FormLayout: Binding loop detected for property "width"
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configGeneral.qml:34:9: QML FormLayout: Binding loop detected for property "width"
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configGeneral.qml:34:9: QML FormLayout: Binding loop detected for property "width"
May 12 23:54:42 odin plasmashell[30055]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:142:5: QML Connections: Detected function "onSettingValueChanged" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
May 12 23:54:44 odin plasmashell[30055]: file:///usr/share/plasma/plasmoids/org.kde.I3Pager/contents/ui/configScreens.qml:15:1: QML ScrollViewKCM: Created graphical object was not placed in the graphics scene.
May 12 23:54:44 odin plasmashell[30055]: qml: Saving config
May 12 23:54:44 odin plasmashell[30055]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:142:5: QML Connections: Detected function "onSettingValueChanged" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
```

The screens list also lists screens which don't have any input, I assume the screens which don't have any input are from those screens which were connected before.

**Comment by duvholt** [comment] 2024-05-13 07:16
>Did you notice that the option show only only workspaces from current screen sometimes doesn't work?

Hmm, no that seemed to work fine for me. I tested with a dual monitor setup but I didn't do any extensive testing.

>However these warnings are there still (not sure which one where there before:

Yeah, I'm not sure if those were there before but either way they should be fixed. Right now it hard to see if we introduce any new errors/warnings.

>The screens list also lists screens which don't have any input, I assume the screens which don't have any input are from those screens which were connected before.

Yep, I think we should somehow mark those screens as disconnected. I still think it makes sense to list all screens as it makes it easier to do relative ordering and see which colors are already used. Unfortunately the list is prune to duplicates as the screen names tend to change on Linux (DP-2 -> DP-2-8-1 etc). If we can retrieve the screen EDID then we should be able to merge screens.

**Comment by duvholt** [comment] 2024-05-13 17:43
>QML FormLayout: Binding loop detected for property "width"

I fixed this warning now (just removed the lines as they didn't seem to do anything).

I think the other warnings are caused by KDE as I see other official plasmoids also log the same warnings. Hopefully it will be fixed in the future.

**Comment by Bureaucromancer** [comment] 2024-06-01 15:08
> Something is breaking the build me, though it’s in i3ipc++. It seems to think that the event hooks aren’t defined… [drmgc/i3ipcpp#43](https://github.com/drmgc/i3ipcpp/issues/43)

With apologies for how old this is, that WAS it; never noticed that Arch is actually building against libsigc++ 2 without an explicit install of 3
